language: node_js
node_js: 
  - "stable"
services:
  - postgresql 
before_script:
  - psql -c 'create database travis_ci_test;' -U postgres
  - psql -c "CREATE USER test_user WITH PASSWORD '';" -U postgres 
  - node ./db/connection.js createAllTables
cache:
  directories:
    - "node_modules"