language: node_js
node_js: 
  - "stable"
services:
  - postgresql 
before_script:
  - cp config/database.travis.yml config/database.yml
  - psql -c 'create database travis_ci_test;' -U postgres
  - psql -c "CREATE USER test_user WITH PASSWORD '';" -U postgres 
  - node ./db/connection.js createAllTables
env:
  - DB_USER=test_user
  - DB_PASS=
  - DB_HOST=localhost
  - DB_PORT=5432
  - DB_NAME=travis_ci_test
cache:
  directories:
    - "node_modules"